[package]
name = "naive_langguesser"
version = "0.1.0"
authors = ["Philipp Gawlik <philipp.gawlik@googlemail.com>"]

[dependencies]
clap = {version = "2.32", features = ["yaml"]}
regex = "1"
lazy_static = "1.2.0"
itertools = "0.8.0"
